version: '3'

services:
  db:
    image: mongo:latest
    restart: always
    container_name: ${MONGO_INITDB_CONTAINER_NAME}
    hostname: mongo_localhost
    env_file:
        - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
      - ./mongodb/log:/var/mongodb