server.port= ${SERVER_PORT}
server.base-path=${SERVER_HOST}

spring.data.mongodb.host=${MONGO_INITDB_HOST}
spring.data.mongodb.port=${MONGO_INITDB_PORT}
spring.data.mongodb.database=${MONGO_INITDB_DATABASE}
#spring.data.mongodb.username=${MONGO_INITDB_ROOT_USERNAME}
#spring.data.mongodb.password=${MONGO_INITDB_ROOT_PASSWORD}


bot_username=${BOT_USERNAME}
bot_token=${BOT_TOKEN}
bot_username_id=${BOT_USERNAME_ID}